PustokMVC/PustokMVC/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PustokMVC.Business.Interfaces;

namespace PustokMVC.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public HeaderViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllAsync(null);

            return View(genres);
        }
    }
}

PustokMVC/PustokMVC/Views/Shared/_BookSliderPartial.cshtml
@model List<Book>

<div class="product-slider multiple-row  slider-border-multiple-row  sb-slick-slider"
     data-slick-setting='{
                            "autoplay": true,
                            "autoplaySpeed": 8000,
                            "slidesToShow": 5,
                            "rows":1,
                            "dots":true
                        }' data-slick-responsive='[
                            {"breakpoint":1200, "settings": {"slidesToShow": 3} },
                            {"breakpoint":768, "settings": {"slidesToShow": 2} },
                            {"breakpoint":480, "settings": {"slidesToShow": 1} },
                            {"breakpoint":320, "settings": {"slidesToShow": 1} }
                        ]'>
    @foreach (var book in Model)
    {
        <div class="single-slide">
            <div class="product-card">
                <div class="product-header">
                    <a asp-action="detail" asp-controller="shop" asp-route-id="@book.Id" class="author">
                        @book.Author.Fullname
                    </a>
                    <h3>
                        <a asp-action="detail" asp-controller="shop" asp-route-id="@book.Id">
                            @book.Title
                        </a>
                    </h3>
                </div>
                <div class="product-card--body">
                    <div class="card-image">
                        <img src="~/uploads/books/@book.BookImages?.FirstOrDefault(x=>x.IsPoster==true)?.ImageUrl" alt="">
                        <div class="hover-contents">
                            <a asp-action="detail" asp-controller="shop" asp-route-id="@book.Id" class="hover-image">
                                <img src="~/uploads/books/@book.BookImages?.FirstOrDefault(x=>x.IsPoster==false)?.ImageUrl" alt="">
                            </a>
                            <div class="hover-btns">
                                <a asp-action="addtobasket" asp-controller="shop" asp-route-bookid="@book.Id" class="single-btn add-to-basket">
                                    <i class="fas fa-shopping-basket"></i>
                                </a>
                                <a href="wishlist.html" class="single-btn">
                                    <i class="fas fa-heart"></i>
                                </a>
                                <a href="compare.html" class="single-btn">
                                    <i class="fas fa-random"></i>
                                </a>
                                <a href="#" data-toggle="modal" data-target="#quickModal"
                                   class="single-btn">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="price-block">
                        <span class="price">£51.20</span>
                        <del class="price-old">£51.20</del>
                        <span class="price-discount">@(book.DiscountPercent)%</span>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

PustokMVC/PustokMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">


<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Pustok - @ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Use Minified Plugins Version For Fast Page Load -->
    <link rel="stylesheet" type="text/css" media="screen" href="~/assets/css/plugins.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/assets/css/main.css" />
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/image/favicon.ico">
</head>

<body>
    <div class="site-wrapper" id="top">
        @await Component.InvokeAsync("Header");
@RenderBody()
</div>
    <section class="section-margin">
        <h2 class="sr-only">Brand Slider</h2>
        <div class="container">
            <div class="brand-slider sb-slick-slider border-top border-bottom" data-slick-setting='{
                                            "autoplay": true,
                                            "autoplaySpeed": 8000,
                                            "slidesToShow": 6
                                            }' data-slick-responsive='[
                {"breakpoint":992, "settings": {"slidesToShow": 4} },
                {"breakpoint":768, "settings": {"slidesToShow": 3} },
                {"breakpoint":575, "settings": {"slidesToShow": 3} },
                {"breakpoint":480, "settings": {"slidesToShow": 2} },
                {"breakpoint":320, "settings": {"slidesToShow": 1} }
            ]'>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-1.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-2.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-3.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-4.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-5.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-6.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-1.jpg" alt="">
                </div>
                <div class="single-slide">
                    <img src="~/assets/image/others/brand-2.jpg" alt="">
                </div>
            </div>
        </div>
    </section>
    <!--=================================
    Footer Area
    ===================================== -->
    <footer class="site-footer">
        <div class="container">
            <div class="row justify-content-between  section-padding">
                <div class=" col-xl-3 col-lg-4 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="brand-footer footer-title">
                            <img src="~/assets/image/logo--footer.png" alt="">
                        </div>
                        <div class="footer-contact">
                            <p>
                                <span class="label">Address:</span><span class="text">
                                    Example Street 98, HH2 BacHa, New
                                    York,
                                    USA
                                </span>
                            </p>
                            <p><span class="label">Phone:</span><span class="text">+18088 234 5678</span></p>
                            <p><span class="label">Email:</span><span class="text">suport@hastech.com</span></p>
                        </div>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-2 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="footer-title">
                            <h3>Information</h3>
                        </div>
                        <ul class="footer-list normal-list">
                            <li><a href="#">Prices drop</a></li>
                            <li><a href="#">New products</a></li>
                            <li><a href="#">Best sales</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-2 col-sm-6">
                    <div class="single-footer pb--40">
                        <div class="footer-title">
                            <h3>Extras</h3>
                        </div>
                        <ul class="footer-list normal-list">
                            <li><a href="#">Delivery</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Stores</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                    </div>
                </div>
                <div class=" col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-title">
                        <h3>Newsletter Subscribe</h3>
                    </div>
                    <div class="newsletter-form mb--30">
                        <form action="https://demo.hasthemes.com/pustok-preview/pustok/php/mail.php">
                            <input type="email" class="form-control" placeholder="Enter Your Email Address Here...">
                            <button class="btn btn--primary w-100">Subscribe</button>
                        </form>
                    </div>
                    <div class="social-block">
                        <h3 class="title">STAY CONNECTED</h3>
                        <ul class="social-list list-inline">
                            <li class="single-social facebook">
                                <a href="#"><i class="ion ion-social-facebook"></i></a>
                            </li>
                            <li class="single-social twitter"><a href="#"><i class="ion ion-social-twitter"></i></a></li>
                            <li class="single-social google">
                                <a href="#">
                                    <i class="ion ion-social-googleplus-outline"></i>
                                </a>
                            </li>
                            <li class="single-social youtube"><a href="#"><i class="ion ion-social-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <p class="copyright-heading">
                    Suspendisse in auctor augue. Cras fermentum est ac fermentum tempor. Etiam
                    vel
                    magna volutpat, posuere eros
                </p>
                <a href="#" class="payment-block">
                    <img src="~/assets/image/icon/payment.png" alt="">
                </a>
                <p class="copyright-text">
                    Copyright © 2019 <a href="#" class="author">Pustok</a>. All Right Reserved.
                    <br>
                    Design By Pustok
                </p>
            </div>
        </div>
    </footer>

    <!-- Use Minified Plugins Version For Fast Page Load -->
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/ajax-mail.js"></script>
    <script src="~/assets/js/custom.js"></script>
    <script src="~/assets/js/main.js"></script>
</body>


</html>